package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "ground",
    srcs = ["ground.cc"],
    deps = [
        "//homework2:pointcloud",
        "@opencv//:core",
        "@opencv//:imgcodecs",
        "@opencv//:imgproc",
        "@opencv//:highgui",
    ],
)
